# Generated by Django 4.2.1 on 2023-07-07 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_question_dislikes_remove_question_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
    ]
